export { default as Home } from "./HomePage";
export { default as About } from "./AboutPage";
export { default as ShopLocal } from "./ShopLocalPage";
export { default as Pricing } from "./PricingPage";
export { default as AddBusiness } from "./AddBusinessPage";
export { default as AddProfessional } from "./AddProfessionalPage";
export { default as ProductsToAvoid } from "./ProductsToAvoidPage";
export { default as Register } from "./RegisterPage";
export { default as SingleShop } from "./SingleShopPage";
