export const GET_SHOPS_BEGIN = "GET_SHOPS_BEGIN";
export const GET_SHOPS_SUCCESS = "GET_SHOPS_SUCCESS";
export const GET_SHOPS_ERROR = "GET_SHOPS_ERROR";
export const GET_SINGLE_SHOP_BEGIN = "GET_SINGLE_SHOP_BEGIN";
export const GET_SINGLE_SHOP_SUCCESS = "GET_SINGLE_SHOP_SUCCESS";
export const GET_SINGLE_SHOP_ERROR = "GET_SINGLE_SHOP_ERROR";
export const LOAD_SHOPS = "LOAD_SHOPS";

export const SET_GRIDVIEW = "SET_GRIDVIEW";
export const SET_LISTVIEW = "SET_LISTVIEW";

export const UPDATE_SORT = "UPDATE_SORT";
export const SORT_SHOPS = "SORT_SHOPS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_SHOPS = "FILTER_SHOPS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
